#!/usr/bin/env python3
"""
extract_docs_data.py — Extract structured data from markdown files.

Scans docs/ and any other markdown-heavy directories for:
- Embedded JSON blocks (```json ... ```)
- Lists (bullet points, numbered)
- Key-value patterns (bold term: definition)
- Headings as hierarchy

Outputs a JSON companion file alongside each markdown file that contains
extractable data, so AIs can consume the data without parsing prose.

Usage:
    python scripts/extract_docs_data.py
    python scripts/extract_docs_data.py --dir docs/geometry
"""

import json, pathlib, re, argparse

ROOT = pathlib.Path(__file__).resolve().parents[1]


def extract_json_blocks(text):
    """Extract all ```json ... ``` code blocks."""
    blocks = []
    for match in re.finditer(r'```json\s*\n(.*?)```', text, re.DOTALL):
        try:
            data = json.loads(match.group(1))
            blocks.append(data)
        except json.JSONDecodeError:
            pass
    return blocks


def extract_python_blocks(text):
    """Extract all ```python ... ``` code blocks as strings."""
    blocks = []
    for match in re.finditer(r'```python\s*\n(.*?)```', text, re.DOTALL):
        blocks.append(match.group(1).strip())
    return blocks


def extract_headings(text):
    """Extract heading hierarchy."""
    headings = []
    for match in re.finditer(r'^(#{1,6})\s+(.+)$', text, re.MULTILINE):
        level = len(match.group(1))
        title = match.group(2).strip()
        headings.append({"level": level, "title": title})
    return headings


def extract_bold_definitions(text):
    """Extract **term:** definition patterns."""
    defs = []
    for match in re.finditer(r'\*\*([^*]+)\*\*[:\s]+([^\n]+)', text):
        term = match.group(1).strip()
        definition = match.group(2).strip()
        if len(definition) > 10:  # skip trivial matches
            defs.append({"term": term, "definition": definition})
    return defs


def extract_bullet_lists(text):
    """Extract bullet-point lists (- or * or numbered)."""
    lists = []
    current_list = []
    for line in text.split("\n"):
        stripped = line.strip()
        if re.match(r'^[-*•]\s+', stripped) or re.match(r'^\d+[.)]\s+', stripped):
            item = re.sub(r'^[-*•\d.)\s]+', '', stripped).strip()
            if item:
                current_list.append(item)
        else:
            if len(current_list) >= 2:  # only capture lists with 2+ items
                lists.append(current_list)
            current_list = []
    if len(current_list) >= 2:
        lists.append(current_list)
    return lists


def extract_formulas(text):
    """Extract mathematical formulas (lines with = signs that look like equations)."""
    formulas = []
    for line in text.split("\n"):
        stripped = line.strip()
        # Match lines that look like formulas: have = and math-like characters
        if "=" in stripped and len(stripped) < 200:
            if re.search(r'[A-Z_][a-z_]*\s*=', stripped) or re.search(r'[λφΣ∫]', stripped):
                if not stripped.startswith("#") and not stripped.startswith("```"):
                    formulas.append(stripped)
    return formulas


def process_file(fp, root):
    """Extract all structured data from a markdown file."""
    try:
        text = fp.read_text(encoding="utf-8")
    except Exception:
        return None

    headings = extract_headings(text)
    json_blocks = extract_json_blocks(text)
    python_blocks = extract_python_blocks(text)
    definitions = extract_bold_definitions(text)
    lists = extract_bullet_lists(text)
    formulas = extract_formulas(text)

    # Only create companion if there's meaningful data
    has_data = (json_blocks or python_blocks or len(definitions) > 3
                or len(formulas) > 2 or len(lists) > 3)

    if not has_data:
        return None

    result = {
        "_source": str(fp.relative_to(root)),
        "_extracted": "auto-generated by scripts/extract_docs_data.py",
        "title": headings[0]["title"] if headings else fp.stem,
        "heading_structure": headings,
    }

    if json_blocks:
        result["embedded_json"] = json_blocks
    if python_blocks:
        result["code_blocks"] = python_blocks
    if definitions:
        result["definitions"] = definitions
    if formulas:
        result["formulas"] = formulas
    if lists:
        result["lists"] = lists

    return result


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", default="docs", help="Directory to scan")
    args = ap.parse_args()

    scan_dir = ROOT / args.dir
    out_dir = ROOT / "data" / "extracted"
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"\n◉ Extracting structured data from {scan_dir}\n")

    md_files = sorted(scan_dir.rglob("*.md"))
    print(f"  Found {len(md_files)} markdown files\n")

    extracted = 0
    skipped = 0

    for fp in md_files:
        result = process_file(fp, ROOT)
        if result is None:
            skipped += 1
            continue

        # Create output path mirroring source structure
        rel = fp.relative_to(ROOT)
        out_path = out_dir / rel.with_suffix(".json")
        out_path.parent.mkdir(parents=True, exist_ok=True)

        out_path.write_text(json.dumps(result, indent=2, ensure_ascii=False) + "\n",
                           encoding="utf-8")

        data_types = []
        if "embedded_json" in result: data_types.append(f"{len(result['embedded_json'])} JSON blocks")
        if "code_blocks" in result: data_types.append(f"{len(result['code_blocks'])} code blocks")
        if "definitions" in result: data_types.append(f"{len(result['definitions'])} definitions")
        if "formulas" in result: data_types.append(f"{len(result['formulas'])} formulas")
        if "lists" in result: data_types.append(f"{len(result['lists'])} lists")

        print(f"  {str(rel):<60} → {', '.join(data_types)}")
        extracted += 1

    print(f"\n  Done: {extracted} files extracted, {skipped} skipped (no structured data)")
    print(f"  Output: {out_dir}/\n")


if __name__ == "__main__":
    main()
